# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App - func-applicationautomation-centralus-001

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  NODE_VERSION: '14.x' # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Resolve Project Dependencies Using Npm'
        shell: bash
        run: |
          npm install -g azure-functions-core-tools@3 --unsafe-perm true

      - name: 'Run Azure Functions Action'
        shell: bash
        run: |
          func azure fsunctionapp publish $appName --build remote

      - name: 'Authenticate with Azure'
        uses: azure/login@v1
        with: 
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: 'Push Configuration Settings'
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          app-settings-json: '${{ secrets.APP_SETTINGS }}'
          general-settings-json: '{"alwaysOn": "false", "webSocketsEnabled": "true"}'
        id: settings
