name: Deploy to Function App

on:
  workflow_dispatch:
  push:
    branches:
      [master]

env:
  AZURE_FUNCTIONAPP_NAME: func-applicationautomation-centralus-001
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '14.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master
    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: 'Resolve Project Dependencies Using Npm'
      shell: bash
      run: |
        npm install
        npm install -g azure-functions-core-tools@3 --unsafe-perm true
        npm run build
    - name: 'Run Azure Functions Action'
      shell: bash
      run: |
        func azure functionapp publish $appName --build remote